language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjoerdk
  password:
    secure: PYRfSn+6UYotMVEbRm2NhOI2fxPBzeXa86ZpY4R0B1tfcKjTm9QD4Xfu35XWpSZpcqNa9LckvMaSPURIVJq4AQJQJfx7PDgCCiUfEvrKelUaV7bFf0lZbl7/qMy2q3bfKVSOE2+/br5b8s1e59WBoTFYKAE6ebBB2RZ6+nY1smI2fTh4UU+/ofeo+L+zr0CkBAyIH/ac3jf0B3eFZ7XVZ7ieZrAysuPbfumxenbCvTbV9s3SzYkMfeu2/LvDw2LLziT3zudZYUzE7Ds9xC5eFKv7uMKopyMinxmn2O35TOV6Q6CWDsUfgEw4tq4UY6juVMnTBoW4HymwXmU7ybw1IdJ9n8nh/l0OPHaWaECx/FF7cFdgXKqUhvRglnTcd3yFY2lANANRAXJ/ICBYzKGpK0H2AyF8LXtmsCHnfoYmwJc8bsMTaiMIOS0cPPzMFLbPjcXETJxcBsmdgCydodndLr0404vneoxSAknj7XZoyBI6TH/LreNbbxe2EMCTMbso3DoauUTvsWzvgrPZ1lWMKskmWnh+jmLEn0p5Cbg84QQr0af9bLhRvVu47dxHd2RWqB4kiVrGF28uFT8K2tKq5zj2gidY78ycT3Fr8GMK+HKP569LGuSBwAJ11jXwaE1kItBGqNYjjn6LsO8iX+/v2yQjaDUZq1yqvgaRMNiOW3c=
  on:
    tags: true
    repo: sjoerdk/wado
    python: 3.6
